version: '3.1'
services:
  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=osticket
      - MYSQL_USER=osticket
      - MYSQL_PASSWORD=osticket
    volumes:
      - ./db:/var/lib/mysql
  osticket:
    build: .
    ports:
      - 8080:80
    depends_on:
      - db
    volumes:
      - ./data:/var/www/html
      - ./apache2:/etc/apache2
